/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.DbCon;

/**
 *
 * @author user
 */
public class DashBoard extends javax.swing.JFrame {

    DbCon con=new DbCon();
    PreparedStatement ps;
    ResultSet rs;
    String sql = "";

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    public float getSalesTotalPrice() {

        float quantity = Float.parseFloat(txtSalesQuantity.getText().trim());
        float unitPrice = Float.parseFloat(txtSalesUnitPrice.getText().trim());
        float totalPrice = quantity * unitPrice;

        return totalPrice;
    }

    public float getActualPrice() {

        float totalPrice = getSalesTotalPrice();
        float discount = Float.parseFloat(txtSalesDiscount.getText().trim());

        float actualPrice = totalPrice - (totalPrice * discount / 100);

        return actualPrice;
    }
// convert util date to sql Date

//    public static java.sql.Date convertUtilDateToSqlDate(java.util.Date utilDate) {
//        if (utilDate != null) {
//            return new java.sql.Date(utilDate.getTime());
//        }
//        return null;
//    }

    public  Date convertUtilDateToSqlDate(java.util.Date  utilDate){
        if(utilDate != null){
            return new Date(utilDate.getTime());
        }
        
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        menu = new javax.swing.JTabbedPane();
        home = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        sales = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        txtSalesProductName = new javax.swing.JTextField();
        txtSalesUnitPrice = new javax.swing.JTextField();
        txtSalesQuantity = new javax.swing.JTextField();
        txtSalesTotalPrice = new javax.swing.JTextField();
        txtSalesDiscount = new javax.swing.JTextField();
        txtSalesActualPrice = new javax.swing.JTextField();
        txtSalesCashReceive = new javax.swing.JTextField();
        txtSalesDueAmount = new javax.swing.JTextField();
        comboSalesCustomerName = new javax.swing.JComboBox<>();
        btnSalesSubmit = new javax.swing.JButton();
        btnSalesReset = new javax.swing.JButton();
        dateSalesdate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        purchase = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jTabbedPane12 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dash Board");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 747, 64));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 747, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 114, -1));

        btnSales.setText("Sales");
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesMouseClicked(evt);
            }
        });
        jPanel2.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 114, -1));

        btnPurchase.setText("Purchase");
        btnPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPurchaseMouseClicked(evt);
            }
        });
        jPanel2.add(btnPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 114, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 390));

        jLabel2.setText("Tab 1");
        home.addTab("tab1", jLabel2);

        menu.addTab("tab1", home);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sales");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 59));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("SID");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        jLabel5.setText("Product Name");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel6.setText("Unit Price");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel7.setText("Quantity");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel8.setText("Total Price");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel9.setText("Discount");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel10.setText("Actual Price");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel11.setText("Cash Received");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel12.setText("Due Amount");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel13.setText("Customer Name");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txtSid.setEditable(false);
        jPanel6.add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));
        jPanel6.add(txtSalesProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        txtSalesUnitPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalesUnitPriceFocusLost(evt);
            }
        });
        jPanel6.add(txtSalesUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        txtSalesQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalesQuantityFocusLost(evt);
            }
        });
        jPanel6.add(txtSalesQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        txtSalesTotalPrice.setEditable(false);
        jPanel6.add(txtSalesTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, -1));

        txtSalesDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalesDiscountFocusLost(evt);
            }
        });
        jPanel6.add(txtSalesDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, -1));

        txtSalesActualPrice.setEditable(false);
        jPanel6.add(txtSalesActualPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, -1));

        txtSalesCashReceive.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalesCashReceiveFocusLost(evt);
            }
        });
        jPanel6.add(txtSalesCashReceive, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, -1));

        txtSalesDueAmount.setEditable(false);
        txtSalesDueAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalesDueAmountActionPerformed(evt);
            }
        });
        jPanel6.add(txtSalesDueAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, -1));

        comboSalesCustomerName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rajib", "Limon", "Mamun", "Hasan", "Tonmoy" }));
        jPanel6.add(comboSalesCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 160, -1));

        btnSalesSubmit.setText("Submit");
        btnSalesSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesSubmitMouseClicked(evt);
            }
        });
        jPanel6.add(btnSalesSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btnSalesReset.setText("Reset");
        jPanel6.add(btnSalesReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));
        jPanel6.add(dateSalesdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, -1));

        jLabel14.setText("Date");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 60, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sales.addTab("tab1", jPanel4);

        menu.addTab("tab2", sales);

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        purchase.addTab("tab1", jPanel3);

        menu.addTab("tab3", purchase);
        menu.addTab("tab4", jTabbedPane11);
        menu.addTab("tab5", jTabbedPane12);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 610, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:

        menu.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseClicked
        // TODO add your handling code here:
        menu.setSelectedIndex(1);
    }//GEN-LAST:event_btnSalesMouseClicked

    private void btnPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPurchaseMouseClicked
        // TODO add your handling code here:
        menu.setSelectedIndex(2);
    }//GEN-LAST:event_btnPurchaseMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setBackground(Color.red);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        btnHome.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnHomeMouseExited

    private void txtSalesDueAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalesDueAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalesDueAmountActionPerformed

    private void txtSalesQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalesQuantityFocusLost
        // TODO add your handling code here:
        // get Total Price from method 
        float totalPrice = getSalesTotalPrice();

        txtSalesTotalPrice.setText(totalPrice + "");
    }//GEN-LAST:event_txtSalesQuantityFocusLost

    private void txtSalesUnitPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalesUnitPriceFocusLost
        // TODO add your handling code here:

        if (txtSalesUnitPrice.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Quantity and Unit price cannot be empty");
            txtSalesUnitPrice.setText(0 + "");
            txtSalesUnitPrice.requestFocus();

        }


    }//GEN-LAST:event_txtSalesUnitPriceFocusLost

    private void txtSalesDiscountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalesDiscountFocusLost
        // TODO add your handling code here:

        float actualPrice = getActualPrice();

        txtSalesActualPrice.setText(actualPrice + "");
    }//GEN-LAST:event_txtSalesDiscountFocusLost

    private void txtSalesCashReceiveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalesCashReceiveFocusLost
        // TODO add your handling code here:
        float actualPrice = getActualPrice();
        float cashReceived = Float.parseFloat(txtSalesCashReceive.getText().trim());

        float dueAmount = actualPrice - cashReceived;

        txtSalesDueAmount.setText(dueAmount + "");
    }//GEN-LAST:event_txtSalesCashReceiveFocusLost

    private void btnSalesSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesSubmitMouseClicked
        // TODO add your handling code here:

        float discountAmount = getSalesTotalPrice() - getActualPrice();

        sql = "insert into sales(name, unitPrice, quantity, actualPrice,"
                + " discount, dueAmount, salerId, salesDate)"
                + "     values(?,?,?,?,?,?,?,?)";

        try {
            ps = con.getCon().prepareStatement(sql);

            ps.setString(1, txtSalesProductName.getText().trim());
            ps.setFloat(2, Float.parseFloat(txtSalesUnitPrice.getText().trim()));
            ps.setFloat(3, Float.parseFloat(txtSalesQuantity.getText().trim()));
            ps.setFloat(4, Float.parseFloat(txtSalesActualPrice.getText().trim()));
            ps.setFloat(5, discountAmount);
            ps.setFloat(6, Float.parseFloat(txtSalesDueAmount.getText()));
            ps.setInt(7, 1);
            ps.setDate(8, convertUtilDateToSqlDate(dateSalesdate.getDate()));

            ps.executeUpdate();

            ps.close();
            con.getCon().close();
            JOptionPane.showMessageDialog(rootPane, "Data Submitted");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Data not Submit");

            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSalesSubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnSalesReset;
    private javax.swing.JButton btnSalesSubmit;
    private javax.swing.JComboBox<String> comboSalesCustomerName;
    private com.toedter.calendar.JDateChooser dateSalesdate;
    private javax.swing.JTabbedPane home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JTabbedPane purchase;
    private javax.swing.JTabbedPane sales;
    private javax.swing.JTextField txtSalesActualPrice;
    private javax.swing.JTextField txtSalesCashReceive;
    private javax.swing.JTextField txtSalesDiscount;
    private javax.swing.JTextField txtSalesDueAmount;
    private javax.swing.JTextField txtSalesProductName;
    private javax.swing.JTextField txtSalesQuantity;
    private javax.swing.JTextField txtSalesTotalPrice;
    private javax.swing.JTextField txtSalesUnitPrice;
    private javax.swing.JTextField txtSid;
    // End of variables declaration//GEN-END:variables
}
